=== regi87/Lenguajes/LENGUAJES DE MARCAS/Examen_LenguajesMarcas_ReginoBoschLozano/XSD/Examen_XSD_ReginoBosch.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Escuela">
      <xs:complexType>
        <xs:sequence>
                  <xs:element name="aula" maxOccurs="unbounded">
                    <xs:element name="nombre_Aula" type="xs:string"/>
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="alumno" maxOccurs="15">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="nombre" type="xs:string"/>
                                <xs:element name="fecha_nacimiento" type="xs:date"/>
                                <xs:element name="aula" type="xs:string"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
        </xs:sequence>
      </xs:complexType>
    </xs:element>
</xs:schema>

=== regi87/Lenguajes/LENGUAJES DE MARCAS/Examen_LenguajesMarcas_ReginoBoschLozano/XML/Examen_XML_ReginoBosch.xml
<?xml version="1.0" encoding="UTF-8"?>
<Escuela xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XSD/Examen_XSD_ReginoBosch.xsd">
    <aula>
      <nombre_Aula>A</nombre_Aula>
                <alumno>
                  <nombre>Paco</nombre>
                  <fecha_nacimiento>1999-1-01</fecha_nacimiento>
                  <aula>A.a</aula>
                </alumno>
                <alumno>
                  <nombre>Juan</nombre>
                  <fecha_nacimiento>1997-1-02</fecha_nacimiento>
                  <aula>A.b</aula>
                </alumno>
    </aula>

    <aula>
      <nombre_Aula>B</nombre_Aula>
                <alumno>
                  <nombre>Miriam</nombre>
                  <fecha_nacimiento>1996-1-03</fecha_nacimiento>
                  <aula>B.a</aula>
                </alumno>
                <alumno>
                  <nombre>Laura</nombre>
                  <fecha_nacimiento>1995-1-01</fecha_nacimiento>
                  <aula>B.b</aula>
                </alumno>
    </aula>
</Escuela>
