//Declaración XML sin DTC
<?xml version="1.0" encoding="utf-8"?>
//TABLA PARA EL EJEMPLO XML
    Transportes Pepe
    Informe de envíos

Descripción: Envíos nacionales
Fecha del informe:15-06-2016

Region    Semestre    Nº de envíos

Norte       1             350
            2             400
Centro      1             500
            2             450
Sur         1             450
            2             400

//EJEMPLO DE XML DE LA TABLA
<transportes>
  <nombre_transporte> </nombre_transporte>
  <informe_envios>
      <nombre_informe> </nombre_informe>
      <descripcion> </descripcion>
      <fecha_informe></fecha_informe>
          <region>
              <nombre_region> </nombre_region>
                  <semestre>
                      <num_semestre> </num_semestre>
                                <envios>
                                  <num_envios></num_envios>
                                </envios>
                  </semestre>
          </region>
  </informe_envios>
</transportes>

//DECLARACIÓN DTD INTERNA
<!DOCTYPE transportes[
//CIERRE             ]>
//DECLARACIÓN DTD EXTERNA
<!DOCTYPE marcadores SYSTEM "Ejer_6_ReginoBoschLozano.dtd">

//DESGLOSE DTD
//EMPEZAMOS DESGLOSANDO DESDE LA ETIQUETA PADRE, TRANSPORES NO HAY QUE ESPECIFICAR
//EL TIPO DE DATO YA QUE NO TIENE DESCRIPCIÓN

<!ELEMENT transportes (nombre_transporte, informe_envios)>

//ELEMENTO ANY SIRVE PARA QUE PUEDA CONTENER CUALQUIER ELEMENTO
<!ELEMENT nombre_transporte ANY>

//EL SIMBOLO + NOS INDICARA QUE EL DATO ES OBLIGATORIO Y REPETIBLE
//EL SIMBOLO ? ES UN CONTENIDO OPCIONAL PUEDE APARECER (UNA VEZ) O NO APARECER
//EL SIMBOLO * OPCIONAL Y REPETIBLE. PUEDE NO APARECER Y PUEDE INCLUSO APARECER VARIAS VECES
    <!ELEMENT informe_envios (nombre_informe, decripcion, fecha_informe+,region)>

//#PCDATA SIGNIFICA QUE EL ELEMENTO PUEDE CONTENER TEXTO
    <!ELEMENT nombre_informe (#PCDATA)>
    <!ELEMENT decripcion (#PCDATA)>
    <!ELEMENT fecha_informe ANY >

    <!ELEMENT region (nombre_region, semestre)>
    <!ELEMENT nombre_region (#PCDATA)>

//ATTLIST NOS PERMITE AÑADIR ATRIBUTOS A LOS ELEMENTOS
//ESTE ATTLIST NOS OBLIGA A QUE SIEMPRE APARECEZCAN LOS ATRIBUTOS NORTE CENTRO SUR OBLIGATORIAMENTE
    <!ATTLIST nombre_region nombre CDATA "Norte  Centro  Sur" #REQUIRED>

    <!ELEMENT semestre (num_semestre, envios)>
    <!ELEMENT num_semetre (#PCDATA)>

//ESTE ATTLIST NOS OBLIGA A QUE SIEMPRE APARECEZCAN LOS ATRIBUTOS NORTE CENTRO SUR OBLIGATORIAMENTE
    <!ATTLIST num_semetre numero CDATA "1  2" #REQUIRED>

    <!ELEMENT envios (num_envios)>
    <!ELEMENT num_envios ANY>
